server {
    listen 80;
    server_name 24aquabooking.ru www.24aquabooking.ru
                manager.24aquabooking.ru
                admin.24aquabooking.ru;
    
    # Редирект на HTTPS (кроме Let's Encrypt)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name 24aquabooking.ru www.24aquabooking.ru;

    ssl_certificate /etc/letsencrypt/live/24aquabooking.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/24aquabooking.ru/privkey.pem;

    # Клиентское приложение
    root /var/www/frontend/mini-app/public/web-client;
    index index.html;

    location /landing {
        alias /var/www/frontend/landing;
        index index.html;
        try_files $uri $uri/index.html =404;
    }

    location /api/ {
        proxy_pass http://backend:8083/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/sync/ws/ {
        proxy_pass http://backend:8083;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ^~ /shared/ {
        alias /var/www/frontend/shared/;
        try_files $uri =404;
    }

    location /uploads/ {
        alias /var/www/shared-uploads/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 443 ssl;
    server_name manager.24aquabooking.ru;

    ssl_certificate /etc/letsencrypt/live/24aquabooking.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/24aquabooking.ru/privkey.pem;

    root /var/www/frontend/manager-panel;
    index index.html;

    location /api/ {
        proxy_pass http://backend:8083/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/sync/ws/ {
        proxy_pass http://backend:8083;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 443 ssl;
    server_name admin.24aquabooking.ru;

    ssl_certificate /etc/letsencrypt/live/24aquabooking.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/24aquabooking.ru/privkey.pem;

    root /var/www/frontend/admin-new;
    index index.html;

    location /api/ {
        proxy_pass http://backend:8083/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
